/* Generated by bin2c, do not edit manually */
#ifndef __level_map_h_included
#define __level_map_h_included

/* Contents of file level_map.bin */
extern const long int level_map_bin_size;
extern const unsigned char level_map_bin[65536];

#endif    /* __level_map_h_included */
