/* Generated by bin2c, do not edit manually */
#ifndef __spring_h_included
#define __spring_h_included

/* Contents of file ./tilemaps/spring.bin */
extern const long int __tilemaps_spring_bin_size;
extern const unsigned char __tilemaps_spring_bin[131072];

#endif    /* __spring_h_included */
